services:
  # postgresql:
  #   container_name: postgresql
  #   image: postgres:latest
  #   volumes:
  #     - ./data/postgresql/:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   networks:
  #     - nodejs_network
  nestjs:
    container_name: nestjs
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
#     networks:
#       - nodejs_network

# networks:
#   docker_network:
#     name: nodejs_network
