services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: ts_user
      POSTGRES_PASSWORD: ts_pass
      POSTGRES_DB: ts_db
    networks:
      - nodejs_network

  nestjs:
    container_name: nestjs
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - nodejs_network

networks:
  nodejs_network:
    name: nodejs_network
